#cloud-config

  # storage:
  #   files:
  #     - filesystem: "root"
  #       path: /opt/bootstrap-coreos.sh
  #       mode: 0755
  #       contents:
  #         remote:
  #           url: "https://raw.githubusercontent.com/anandr781/Kube-CoreOS/master/bootstrap-coreos.sh"
  
hostname: "CoreOS-I"
manage_etc_hosts: "CoreOS-I"

passwd:
  users: 
    - name: anand
      password_hash: $1$SaltSalt$RGf7fuaiqdasXWS5enP7F/
      ssh_authorized_keys:
         - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAjYQpHOuiWOYjWiF5HJejHMB0gDjCSZSHqTnfw6nrrjeYNPj2JmnpxTFOUa34gdNJ8pHMSMwWIOTd0ofFfo7t0VKO3UTSwxjjSWB/VeuQojqGNJKv+zw0nx26m3pvOWWHc66PiEWsPvGr7Q4NZt/rZNPYdcAG/ra0/FVCnjDTPEplLzZFm5GfiXLuSa/HRcDlfShdlrL1RV7MGPMCMb/ggjrs3JwkjuCd2aTrdjUl1DT78t0LWXnkJDmht9jSA/iAIhP8CAsI/Q+uHyqdnejc2VOdAVLGnyANRUATQtzUBkxpzZIe2K489eiCvFw1ELsR5PLg4gYhhaj0faCd9me35w== rsa-key-20180409
      groups: 
       - sudo
       - docker

coreos:
    units:
      - name: etcd-member.service
        command: stop

      - name: etcd.service
        command: stop
        mask: true
        
     #rpc-statd.service is a necessary dependency for NFS client service (docker-vol-data.mount) to work   
      - name: rpc-statd.service
        command: start
        
      - name: docker-vol-data.mount
        command: start
        content: | 
           [Mount]
           What=192.168.10.103:/mnt/SATA500GB-V1/SecondaryStorage1-NFS/CoreOS-I
           Where=/var/lib
           Type=nfs
           Options=vers=4,sec=sys,noauto 

     #start only docker and docker-socket
      - name: docker.service
        enable: true
        command: start

      - name: docker-tcp.socket
        enable: true
        content: |
          [Unit]
          Description=Docker Socket for the API
          [Socket] 
          ListenStream=2375
          BindIPv6Only=both
          Service=docker.service
          [Install]
          WantedBy=sockets.target

      - name: iscsid.service
        enable: true
        command: "start"
        write_files:
           - path: "/etc/iscsi/iscsid.conf"
             permissions: "0644"
             owner: "root"
             content: |
               isns.address = 192.168.10.103
               isns.port = 3260
               # node.session.auth.username = my_username
               # discovery.sendtargets.auth.username = my_username
               # node.session.auth.password = my_secret_password
               # discovery.sendtargets.auth.password = my_secret_password

      - name: settimezone.service
        command: start
        content: |
           [Unit]
           Description=Set the time zone

           [Service]
           ExecStart=/usr/bin/timedatectl set-timezone Asia/Calcutta
           RemainAfterExit=yes
           Type=oneshot        

      - name: systemd-timesyncd.service
        command: stop
        mask: true
      - name: ntpd.service
        command: start
        enable: true        
        write_files:
          - path: /etc/ntp.conf
            content: |
              server 0.in.pool.ntp.org
              server 3.asia.pool.ntp.org
              server 2.asia.pool.ntp.org

              # - Allow only time queries, at a limited rate.
              # - Allow all local queries (IPv4, IPv6)
              restrict default nomodify nopeer noquery limited kod
              restrict 127.0.0.1
              restrict [::1]
