#cloud-config

  # storage:
  #   files:
  #     - filesystem: "root"
  #       path: /opt/bootstrap-coreos.sh
  #       mode: 0755
  #       contents:
  #         remote:
  #           url: "https://raw.githubusercontent.com/anandr781/Kube-CoreOS/master/bootstrap-coreos.sh"
# hostname: "CoreOS-I"
# manage_etc_hosts: "CoreOS-I"

passwd:
  users: 
    - name: anand
      password_hash: $1$SaltSalt$RGf7fuaiqdasXWS5enP7F/
      ssh_authorized_keys:
         - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAjYQpHOuiWOYjWiF5HJejHMB0gDjCSZSHqTnfw6nrrjeYNPj2JmnpxTFOUa34gdNJ8pHMSMwWIOTd0ofFfo7t0VKO3UTSwxjjSWB/VeuQojqGNJKv+zw0nx26m3pvOWWHc66PiEWsPvGr7Q4NZt/rZNPYdcAG/ra0/FVCnjDTPEplLzZFm5GfiXLuSa/HRcDlfShdlrL1RV7MGPMCMb/ggjrs3JwkjuCd2aTrdjUl1DT78t0LWXnkJDmht9jSA/iAIhP8CAsI/Q+uHyqdnejc2VOdAVLGnyANRUATQtzUBkxpzZIe2K489eiCvFw1ELsR5PLg4gYhhaj0faCd9me35w== rsa-key-20180409
      groups: 
       - sudo
       - docker

systemd:
    units:
      - name: etcd-member.service
        enable: false

      - name: etcd.service
        enable: false
        mask: true

     
        
     #rpc-statd.service is a necessary dependency for NFS client service (docker-vol-data.mount) to work   
      - name: rpc-statd.service
        enable: true  
      - name: var-lib.mount
        enable: true
        contents: | 
           [Unit]
           Description=Unit file to mount NFS share for docker volume 
           Before=remote-fs.target
           [Mount]
           What=192.168.10.103:/mnt/SATA500GB-V1/SecondaryStorage1-NFS/CoreOS-I
           Where=/var/lib
           Type=nfs
           [Install]
           WantedBy=remote-fs.target

     #start only docker and docker-socket
      - name: docker.service
        enable: true

      - name: docker-tcp.socket
        enable: true
        contents: |
          [Unit]
          Description=Docker Socket for the API
          [Socket] 
          ListenStream=2375
          BindIPv6Only=both
          Service=docker.service
          [Install]
          WantedBy=sockets.target

      - name: iscsid.service
        enable: true
networkd:
    units:
      - name: static.network
        contents: |
          [Match]
          Name=eth1

          [Network]
          Address=192.168.10.105/24
          Gateway=192.168.10.1
