#cloud-config

storage:
  files:
    - filesystem: "root"
      path: /opt/bootstrap-coreos.sh
      mode: 0755
      contents:
        remote:
          url: "https://raw.githubusercontent.com/anandr781/Kube-CoreOS/master/bootstrap-coreos.sh"

passwd:
  users: 
    - name: anand
      password_hash: $1$DF2V.llN$6YMarev0CDiq2myyMWo161
      ssh_authorized_keys:
         - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAjYQpHOuiWOYjWiF5HJejHMB0gDjCSZSHqTnfw6nrrjeYNPj2JmnpxTFOUa34gdNJ8pHMSMwWIOTd0ofFfo7t0VKO3UTSwxjjSWB/VeuQojqGNJKv+zw0nx26m3pvOWWHc66PiEWsPvGr7Q4NZt/rZNPYdcAG/ra0/FVCnjDTPEplLzZFm5GfiXLuSa/HRcDlfShdlrL1RV7MGPMCMb/ggjrs3JwkjuCd2aTrdjUl1DT78t0LWXnkJDmht9jSA/iAIhP8CAsI/Q+uHyqdnejc2VOdAVLGnyANRUATQtzUBkxpzZIe2K489eiCvFw1ELsR5PLg4gYhhaj0faCd9me35w== rsa-key-20180409
      groups: 
       - sudo
       - docker

systemd:
    units:
      - name: etcd.service
        mask: true
           
      - name: etcd-member.service
        enable: true
        dropins: 
          - name: 20-clct-etcd-member.conf
            contents: |
              [Service]
              RestartSec=120s
              Restart=on-failure
              EnvironmentFile=/etc/systemd/system/etcd-member.service.d/etcd-member-env.env
              
      - name: flanneld.service
        enable: true
        dropins:
          - name: 50-network-config.conf
            contents: |
              [Unit]
              Requires=etcd-member.service
              After=etcd-member.service
              
              [Service]
              RestartSec=30s
              Restart=always
              ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "10.5.0.0/16" , "Backend": {"Type": "vxlan"} }'
      
      - name: docker.service
        enable: true
        dropins:
          - name: 60-docker-dependencies.conf
            contents: |
              [Unit]
              After=flanneld.service
              Requires=flanneld.service
 
              [Service]
              Restart=always
      
      - name: docker-tcp.socket
        enable: true
        contents: |
          [Unit]
          Description=Docker Socket for the API

          [Socket] 
          ListenStream=2375
          BindIPv6Only=both
          Service=docker.service

          [Install]
          WantedBy=sockets.target
